[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:apache]
command=/usr/local/bin/apache2-foreground
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:reverb]
command=/usr/local/bin/php artisan reverb:start --host=127.0.0.1 --port=8080
directory=/var/www/html
user=www-data
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
